name = "twitter-briefing"
main = "src/index.ts"
compatibility_date = "2024-06-20"
account_id = "0e1651bc459f3017e816ba2263e0807a"

[[kv_namespaces]]
binding = "BRIEFING"
id = "e7bbcf8e214d4586afb9749c4e0dd349"
